tab:
    id: home
    name: Products
panel:
    action: product_category
    replace_id: product_category
    name: Show All Categories
form:
    tid: productTable
    class: uniCreate
    action: create_product
    fields:
        - element: input
          label: URL
          type: url
          name: url
        - element: input
          label: Key Words
          type: text
          name: key_words
        - element: button
          content: Submit
          type: submit
table:
    heads: [ Picture, Name, Actions]
    body:
        id: productTable
